### ISSUE TITLE
Weak reference

### ISSUE THREAD

**Issue by OmiCron07** [KuraiAndras/MediatR.Courier#1]
Did you already think to use weak references when subscribing the subscribers? It should avoid the need to unsubscribe them. WeakReference class (https://docs.microsoft.com/en-us/dotnet/api/system.weakreference?view=net-5.0) or week event pattern (https://docs.microsoft.com/en-us/dotnet/api/system.weakreference?view=net-5.0) can be used.

**Comment by KuraiAndras** [comment]
I have considered it initially, but never got to try it out properly. I will look into it in the following days

**Comment by OmiCron07** [comment]
Do you have an update about this?

**Comment by KuraiAndras** [comment]
Sorry, I forgot about it. I'll get back on this soon

**Comment by OmiCron07** [comment]
I confirm that the latest version fixed the case of multiple calls on my delegates, even when the windows were closed.

**Comment by OmiCron07** [comment]
After more testing, I have a concern. I have a callback called twice probably because of low memory strain and so, not garbage collected. 

Do you think that you should add a garbage collection in the Handle method or should I add one when closing a window?

**Comment by KuraiAndras** [comment]
The problem with manually triggering GC is that it is not deterministic and hard to make it work reliably. Creating some code around GC collection in the handle method would probably slow it down and it might create some hard to catch bugs (not to mention weird race conditions). Of course, you can trigger GC collection manually after windows are closed, but after experimenting with it in the tests and the sample app I would advise against it.
What I would do is either manually unsubscribe or work around multiple subscriptions. Also make sure that the places where the objects are not collected can be solved by triggering GC - you might have some other class reference your handler which is in turn not collected.
