### ISSUE TITLE
Notification callback thread context

### ISSUE THREAD

**Issue by OmiCron07** [KuraiAndras/MediatR.Courier#2]
Shouldn't the callback be guaranteed to run on the same thread context of the publish (ConfigureAwait(true)) ? I have a WPF app that has to execute the notification on the UI/STA thread and Courier does not guarantee that. The notification is triggered from the UI thread and the handler is on the UI thread too. Do I have to implement a context switching mechanism for each notification?

**Comment by KuraiAndras** [comment]
In the past I did that - a dispatcher which could dispatch to the WPF main thread, and another one for Unity. I guess this should be configurable. I'll try to create a new version soon

**Comment by OmiCron07** [comment]
Is it done by your last version?

**Comment by KuraiAndras** [comment]
Yes. You can configure the behaviour through the CourierOptions class, either when instantiating the courier or when you register it.
