### ISSUE TITLE
Missing dependencies with MediatR version 10

### ISSUE THREAD

**Issue by OmiCron07** [KuraiAndras/MediatR.Courier#6]
MediatR version 10 moved the INotification interface into a new assembly MediatR.Contracts, so, using the latest MediatR without referencing that new assembly breaks the compilation of the application.

**Comment by OmiCron07** [comment]
MediatR issue: https://github.com/jbogard/MediatR/issues/690

**Comment by KuraiAndras** [comment]
@OmiCron07 Can you test that the 5.0.0 preview works for you? https://www.nuget.org/packages/MediatR.Courier/5.0.0-preview0001

**Comment by OmiCron07** [comment]
It compiles and executes!

**Comment by KuraiAndras** [comment]
Thats great i will release a stable version soon

**Comment by KuraiAndras** [comment]
the 5.0.0 release fixes this
